{{- if not .Values.etcd.enabled }}
{{- if .Values.externalEtcd.tls.certBase64Encoded }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bk-hcm.etcdSecretName" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- if .Values.externalEtcd.tls.caBase64Encoded }}
  {{ .Values.externalEtcd.tls.caCertFileName }}: {{ .Values.externalEtcd.tls.caBase64Encoded }}
  {{- end }}
  {{- if .Values.externalEtcd.tls.certBase64Encoded }}
  {{ .Values.externalEtcd.tls.certFileName }}: {{ .Values.externalEtcd.tls.certBase64Encoded }}
  {{- end }}
  {{- if .Values.externalEtcd.tls.keyBase64Encoded }}
  {{ .Values.externalEtcd.tls.keyFileName }}: {{ .Values.externalEtcd.tls.keyBase64Encoded }}
  {{- end }}
{{- end }}
{{- end }}
