version: v2.0

resources:
  repositories:
    - repository: ci_templates/public/codecc
      name: codecc

stages:
  - name: "stage1"
    check-out:
      gates:
        - template: commonGate.yml@codecc
      timeout-hours: 10
    jobs:
      template:
        - name: openScan.yml@codecc
