apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "bk-hcm.fullname" . }}-cloudserver
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.cloudserver.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        component: cloudserver
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/cloudserver/configmap.yaml") . | sha256sum }}
      {{- if .Values.cloudserver.podAnnotations }}
        {{ toYaml .Values.cloudserver.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "bk-hcm.serviceAccountName" . }}
      {{- with .Values.cloudserver.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.cloudserver.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.cloudserver.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      initContainers:
        {{- include "bk-hcm.wait-for-pod-init-container" (list . (printf "%s-dataservice" (include "bk-hcm.fullname" .)) "-lcomponent=dataservice") | nindent 8 }}
        {{- include "bk-hcm.wait-for-pod-init-container" (list . (printf "%s-authserver" (include "bk-hcm.fullname" .)) "-lcomponent=authserver") | nindent 8 }}
        {{- include "bk-hcm.wait-for-pod-init-container" (list . (printf "%s-hcservice" (include "bk-hcm.fullname" .)) "-lcomponent=hcservice") | nindent 8 }}
      containers:
        - name: cloudserver
          image: {{ .Values.global.imageRegistry }}/{{ .Values.cloudserver.image.repository }}:v{{ default .Values.global.imageTag .Values.cloudserver.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          command:
            - /data/hcm/bk-hcm-cloudserver
            - --bind-ip=$(POD_IP)
            - --config-file=/data/hcm/etc/config.yaml
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.cloudserver.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.cloudserver.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          {{- if .Values.cloudserver.resources }}
          resources: {{ toYaml .Values.cloudserver.resources | nindent 12 }}
          {{- end }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if .Values.cloudserver.env -}}
            {{ toYaml .Values.cloudserver.env | indent 10 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.cloudserver.port }}
          volumeMounts:
            - mountPath: /data/hcm/etc
              name: config
            {{- if not .Values.etcd.enabled }}
            - mountPath: /data/hcm/etc/certs
              name:  etcd-certs
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "bk-hcm.fullname" . }}-cloudserver-config
      {{- if not .Values.etcd.enabled }}
        - name: etcd-certs
          secret:
            secretName: {{ template "bk-hcm.etcdSecretName" . }}
      {{- end }}
