swagger: '2.0'
basePath: /
info:
  version: '0.1'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /api/v1/cloud/accounts/extensions/list:
    post:
      operationId: list_account_with_extension
      description: ''
      tags: []
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /{env.url_path_prefix}api/v1/cloud/accounts/extensions/list
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: true
        disabledStages: []
        descriptionEn:
  /api/v1/cloud/accounts/secrets/list:
    post:
      operationId: list_secret_key
      description: ''
      tags: []
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /{env.url_path_prefix}api/v1/cloud/accounts/secrets/list
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: true
        disabledStages: []
        descriptionEn:
