{{- if .Values.authRegister.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "bk-hcm.fullname" . }}-auth-register-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  ttlSecondsAfterFinished: 600
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "bk-hcm.serviceAccountName" . }}
      initContainers:
        {{- include "bk-hcm.wait-for-pod-init-container" (list . (printf "%s-authserver" (include "bk-hcm.fullname" .)) (include "bk-hcm.authserver-pod-selector" .)) | nindent 8 }}
      containers:
        - name: auth-register
          image: {{ default .Values.global.imageRegistry .Values.image.registry}}/{{ .Values.authRegister.image.repository }}:v{{ default .Values.image.tag .Values.authRegister.image.tag }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.image.pullPolicy | quote }}
          command: ["/data/bin/auth-register.sh"]
          env:
            - name: BK_APP_CODE
              value: {{ .Values.appCode }}
            - name: BK_AUTH_USER_NAME
              value: {{ .Values.authRegister.userName }}
            - name: BK_TENANT_ID
              value: {{ include "bk-hcm.tenantID" . }}
            - name: BK_AUTHSERVER_HOST
              value: {{ include "authserverIngressHost" . }}
            - name: BK_AUTHSERVER_ENDPOINT
              value: {{ include "bk-hcm.authserver" . }}
          resources: {{ toYaml .Values.authRegister.resources | nindent 12 }}
      restartPolicy: OnFailure
  backoffLimit: 20
{{- end }}
