apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bk-hcm.fullname" . }}-authserver-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  config.yaml: |-
    network:
      bindIP:
      port: {{ .Values.authserver.port}}
      tls:
        insecureSkipVerify:
        certFile:
        keyFile:
        caFile:
        password:
    service:
      etcd:
        {{- include "common.tplvalues.render" (dict "value" (include "bk-hcm.etcdConfig" .) "context" $) | nindent 8 }}
    log:
      {{- toYaml .Values.authserver.log | nindent 6 }}
    iam:
      endpoints:
        - {{ .Values.bkIamApiUrl }}
      appCode: {{ .Values.appCode }}
      appSecret: {{ .Values.appSecret }}
      tls:
        insecureSkipVerify:
        certFile:
        keyFile:
        caFile:
        password:
    esb:
      endpoints:
        - {{ .Values.bkComponentApiUrl }}
      appCode: {{ .Values.appCode }}
      appSecret: {{ .Values.appSecret }}
      user: admin
      tls:
        insecureSkipVerify:
        certFile:
        keyFile:
        caFile:
        password:
    tenant:
      {{- toYaml .Values.tenant | nindent 6 }}
    cmdb:
      {{- toYaml .Values.cmdb | nindent 6 }}
