apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bk-hcm.fullname" . }}-dataservice-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  config.yaml: |-
    network:
      bindIP:
      port: {{ .Values.dataservice.port}}
      tls:
        insecureSkipVerify:
        certFile:
        keyFile:
        caFile:
        password:
    service:
      etcd:
        {{- include "common.tplvalues.render" (dict "value" (include "bk-hcm.etcdConfig" .) "context" $) | nindent 8 }}
    log:
      {{- toYaml .Values.dataservice.log | nindent 6 }}
    database:
      {{- include "common.tplvalues.render" (dict "value" (include "bk-hcm.databaseConfig" .) "context" $) | nindent 6 }}
    esb:
      endpoints:
        - {{ .Values.bkComponentApiUrl }}
      appCode: {{ .Values.appCode }}
      appSecret: {{ .Values.appSecret }}
      user: admin
      tls:
        insecureSkipVerify:
        certFile:
        keyFile:
        caFile:
        password:
    crypto:
      aesGcm:
        key: {{ .Values.crypto.aesGcm.key }}
        nonce: {{ .Values.crypto.aesGcm.nonce }}
    objectstore:
      {{- toYaml .Values.objectstore | nindent 6 }}
