apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "bk-hcm.fullname" . }}-apiserver
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiserver.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        component: apiserver
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/apiserver/configmap.yaml") . | sha256sum }}
      {{- if .Values.apiserver.podAnnotations }}
        {{- toYaml .Values.apiserver.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "bk-hcm.serviceAccountName" . }}
      {{- with .Values.apiserver.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
          {{- toYaml . |nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "bk-hcm.wait-for-pod-init-container" (list . (printf "%s-cloudserver" (include "bk-hcm.fullname" .)) "-lcomponent=cloudserver") | nindent 8 }}
      containers:
        - name: apiserver
          image: {{ default .Values.global.imageRegistry .Values.image.registry}}/{{ .Values.apiserver.image.repository }}:v{{ default .Values.image.tag .Values.apiserver.image.tag }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.image.pullPolicy | quote }}
          command:
            - /data/hcm/bk-hcm-apiserver
            - --bind-ip=$(POD_IP)
            - --config-file=/data/hcm/etc/config.yaml
            - --disable-jwt={{ .Values.apiserver.disableJwt }}
            {{- if not .Values.apiserver.disableJwt }}
            - --public-key=/data/hcm/etc/apigw_public.key
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.apiserver.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.apiserver.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          {{- if .Values.apiserver.resources }}
          resources: {{ toYaml .Values.apiserver.resources | nindent 12 }}
          {{- end }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if .Values.apiserver.env -}}
            {{ toYaml .Values.apiserver.env | indent 10 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.apiserver.port }}
          volumeMounts:
            - mountPath: /data/hcm/etc/config.yaml
              name: config
              subPath: config.yaml
            {{- if not .Values.apiserver.disableJwt }}
            - mountPath: /data/hcm/etc/apigw_public.key
              name:  config
              subPath: apigw_public.key
            {{- end }}
            {{- if not .Values.etcd.enabled }}
            {{- if .Values.externalEtcd.tls.enabled }}
            - mountPath: /data/hcm/etc/certs
              name:  etcd-certs
            {{- end }}
            {{- end }}

      volumes:
        - name: config
          configMap:
            name: {{ template "bk-hcm.fullname" . }}-apiserver-config
            items:
              - key: config.yaml
                path: config.yaml
            {{- if not .Values.apiserver.disableJwt }}
              - key: apigw_public.key
                path: apigw_public.key
            {{- end }}
      {{- if not .Values.etcd.enabled }}
      {{- if .Values.externalEtcd.tls.enabled }}
        - name: etcd-certs
          secret:
            secretName: {{ template "bk-hcm.etcdSecretName" . }}
      {{- end }}
      {{- end }}
