apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bk-hcm.fullname" . }}-hcservice-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  config.yaml: |-
    network:
      bindIP:
      port: {{ .Values.hcservice.port}}
      tls:
        insecureSkipVerify:
        certFile:
        keyFile:
        caFile:
        password:
    service:
      etcd:
        {{- include "common.tplvalues.render" (dict "value" (include "bk-hcm.etcdConfig" .) "context" $) | nindent 8 }}
    log:
      {{- toYaml .Values.hcservice.log | nindent 6 }}
    sync:
      {{- toYaml .Values.hcservice.sync | nindent 6 }}
    tenant:
      {{- toYaml .Values.tenant | nindent 6 }}
